alias verk="cd ~/verk/btr-email"
alias mnt="cd /mnt/shared/btr-data"
alias sub="sublime_text"
alias fs="sshfs max@dev2.recoset.com:/ ~/mount"
alias dev2="ssh -X max@dev2.recoset.com"
alias jc="javac -d classes *.java"
alias jr="java -cp classes"