alias verk="cd ~/verk/btr-email"
alias mnt="cd /mnt/shared/btr-data"
alias sub="sublime_text"
alias fsdev2="sshfs max@dev2.recoset.com:/home/max/ ~/dev2mount"
alias fsag2="sshfs max@ag2.recoset.com:/home/max/ ~/ag2mount"
alias dev="ssh -X max@dev.recoset.com"
alias dev2="ssh -X max@dev2.recoset.com"
alias jc="javac -d classes *.java"
alias jr="java -cp classes"
alias ag2="ssh -X max@ag2.recoset.com"

